[package]
name = "coast-to-coast"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.33.2"
egui = "0.33.2"
resvg = "0.41"
usvg = { version = "0.41", default-features = false }
tiny-skia = "0.11"
egui_extras = { version = "0.33.2", features = ["image"] }
fontdb = "0.16"